// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxjiehpljagofuporpgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4amllaHBsamFnb2Z1cG9ycGdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mjg5MDIsImV4cCI6MjA2NDUwNDkwMn0.-1rTxeWWl3wd3f9Gskg5dhlUxqpa3eCKobdK1T3RbG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);